[workspace]
resolver = "2"
members = ["crates/torture-cli", "crates/torture-parser"]

[workspace.dependencies]
torture-parser = { path = "crates/torture-parser" }
masterbundle-collector = { git = "https://github.com/UnturnedIndexer/masterbundle-collector.git" }
anyhow = "1.0.86"
